Repository fga-gpp-mds/2018.1_Nexte, pull requests merged in 2018-05, with the labels that each got.

#261 Feature/115
  docs/MDS/DocArquitetura.md
  docs/MDS/DocDiagram/CommentsDiagram.asta
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsInteractor.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsView.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/res/layout/activity_comments.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeViewTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsViewTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileModelTest.kt
Labels: code, development team, easy, enhancement

#262 Feature/252
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeView.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsView.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileView.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedView.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedWorker.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListView.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginView.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileView.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeViewTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsViewTest.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileViewTest.kt
  project/app/src/test/java/com/nexte/nexte/ExampleUnitTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedViewTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListViewTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginViewTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingViewTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileViewTest.kt
Labels: code, development team, enhancement, eps

#277 Feature/114
  docs/MDS/DocArquitetura.md
  docs/MDS/DocDiagram/MatchDiagram.asta
  project/app/build.gradle
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/MatchModelTestTest.kt
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/calendar_logo-web.png
  project/app/src/main/clock_logo-web.png
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/User.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchInteractor.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchModel.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchPresenter.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchView.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchWorker.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileView.kt
  project/app/src/main/res/drawable/ic_launcher_background.xml
  project/app/src/main/res/layout/activity_main.xml
  project/app/src/main/res/layout/activity_match.xml
  project/app/src/main/res/layout/row_match_info.xml
  project/app/src/main/res/layout/row_match_sets.xml
  project/app/src/main/res/layout/row_match_time.xml
  project/app/src/main/res/layout/row_match_wo.xml
  project/app/src/main/res/mipmap-anydpi-v26/calendar_logo.xml
  project/app/src/main/res/mipmap-anydpi-v26/calendar_logo_round.xml
  project/app/src/main/res/mipmap-anydpi-v26/clock_logo.xml
  project/app/src/main/res/mipmap-anydpi-v26/clock_logo_round.xml
  project/app/src/main/res/mipmap-hdpi/calendar_logo.png
  project/app/src/main/res/mipmap-hdpi/calendar_logo_round.png
  project/app/src/main/res/mipmap-hdpi/clock_logo.png
  project/app/src/main/res/mipmap-hdpi/clock_logo_round.png
  project/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-mdpi/calendar_logo.png
  project/app/src/main/res/mipmap-mdpi/calendar_logo_round.png
  project/app/src/main/res/mipmap-mdpi/clock_logo.png
  project/app/src/main/res/mipmap-mdpi/clock_logo_round.png
  project/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-xhdpi/calendar_logo.png
  project/app/src/main/res/mipmap-xhdpi/calendar_logo_round.png
  project/app/src/main/res/mipmap-xhdpi/clock_logo.png
  project/app/src/main/res/mipmap-xhdpi/clock_logo_round.png
  project/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-xxhdpi/calendar_logo.png
  project/app/src/main/res/mipmap-xxhdpi/calendar_logo_round.png
  project/app/src/main/res/mipmap-xxhdpi/clock_logo.png
  project/app/src/main/res/mipmap-xxhdpi/clock_logo_round.png
  project/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-xxxhdpi/calendar_logo.png
  project/app/src/main/res/mipmap-xxxhdpi/calendar_logo_round.png
  project/app/src/main/res/mipmap-xxxhdpi/clock_logo.png
  project/app/src/main/res/mipmap-xxxhdpi/clock_logo_round.png
  project/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  project/app/src/main/res/values/colors.xml
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchModelTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchWorkerTest.kt
  project/build.gradle
Labels: code, development team, hard

#288 Feature/287
  docs/Sprints/Sprint9/Sprint9-Planejamento.md
  mkdocs.yml
Labels: documentation, easy, eps, scrum master

#272 feature/250
  docs/EPS/EAP.md
  docs/EPS/RoadMap.md
Labels: documentation, easy, eps

#290 Feature/275
  docs/MDS/DocArquitetura.md
  docs/MDS/DocDiagram/CommentsDiagram.asta
  project/app/ect.iml app app.iml .gradle build generated source kapt debug apt r aidl buildConfig rs resValues debugAnd
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsInteractor.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsView.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/Mocker/CommentsMocker.java
  project/app/src/main/res/layout/row_comments.xml
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsViewTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
Labels: code

#291 Feature/249
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListInteractor.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListView.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListWorker.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListViewTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListWorkerTest.kt
Labels: code, development team, easy, eps

#309 Feature/120
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeModel.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeView.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeWorker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchFragment.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchModel.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchPresenter.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchWorker.kt
  project/app/src/main/res/layout/activity_challenger.xml
  project/app/src/main/res/layout/activity_challenger_sent.xml
  project/app/src/main/res/layout/activity_match.xml
  project/app/src/main/res/layout/fragment_nochallenge.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengePresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeViewTest.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileModelTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedModelTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchModelTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchWorkerTest.kt
Labels: mds

#320 Feature/311
  docs/Sprints/Sprint10/Sprint10-Planejmento.md
  docs/Sprints/Sprint10/Sprint10-Resultados.md
  docs/Sprints/Sprint11/Sprint11-Planejamento.md
  mkdocs.yml
Labels: documentation, easy, eps, scrum master

#321 Feature/307
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchFragment.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchInteractor.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchModel.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchPresenter.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchWorker.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchModelTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchWorkerTest.kt
Labels: code, development team, enhancement, eps

#322 Feature/140
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedFragment.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedManager.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedModel.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedPresenter.kt
  project/app/src/main/res/drawable/background_bar_botton_rounded.xml
  project/app/src/main/res/layout/activity_feed_view.xml
  project/app/src/main/res/layout/activity_main.xml
  project/app/src/main/res/layout/activity_show_profile.xml
  project/app/src/main/res/layout/row_feed.xml
  project/app/src/main/res/menu/bottom_navigation.xml
  project/app/src/main/res/mipmap-hdpi/feed_comment.png
  project/app/src/main/res/mipmap-hdpi/feed_like.png
  project/app/src/main/res/mipmap-hdpi/feed_like_fill.png
  project/app/src/main/res/mipmap-mdpi/feed_comment.png
  project/app/src/main/res/mipmap-mdpi/feed_like.png
  project/app/src/main/res/mipmap-mdpi/feed_like_fill.png
  project/app/src/main/res/mipmap-xhdpi/feed_comment.png
  project/app/src/main/res/mipmap-xhdpi/feed_like.png
  project/app/src/main/res/mipmap-xhdpi/feed_like_fill.png
  project/app/src/main/res/mipmap-xxhdpi/feed_comment.png
  project/app/src/main/res/mipmap-xxhdpi/feed_like.png
  project/app/src/main/res/mipmap-xxhdpi/feed_like_fill.png
  project/app/src/main/res/mipmap-xxxhdpi/feed_comment.png
  project/app/src/main/res/mipmap-xxxhdpi/feed_like.png
  project/app/src/main/res/mipmap-xxxhdpi/feed_like_fill.png
  project/app/src/main/res/values/colors.xml
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedModelTest.kt
Labels: code, design, development team, easy, eps, mds

#332 Feature/124
  project/app/src/androidTest/java/com/nexte/nexte/CommentsViewTest.java
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/check_comments-web.png
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeView.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsFragment.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsInteractor.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedFragment.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/res/drawable/check_comments_background.xml
  project/app/src/main/res/layout/activity_challenger.xml
  project/app/src/main/res/layout/activity_comments.xml
  project/app/src/main/res/layout/row_comments.xml
  project/app/src/main/res/layout/row_match_sets.xml
  project/app/src/main/res/layout/row_match_time.xml
  project/app/src/main/res/mipmap-anydpi-v26/check_comments.xml
  project/app/src/main/res/mipmap-anydpi-v26/check_comments_round.xml
  project/app/src/main/res/mipmap-hdpi/check.png
  project/app/src/main/res/mipmap-hdpi/check_comments.png
  project/app/src/main/res/mipmap-hdpi/check_comments_foreground.png
  project/app/src/main/res/mipmap-hdpi/check_comments_round.png
  project/app/src/main/res/mipmap-hdpi/direct_hdpi.png
  project/app/src/main/res/mipmap-mdpi/check_comments.png
  project/app/src/main/res/mipmap-mdpi/check_comments_foreground.png
  project/app/src/main/res/mipmap-mdpi/check_comments_round.png
  project/app/src/main/res/mipmap-mdpi/check_mdpi.png
  project/app/src/main/res/mipmap-mdpi/direct_mdpi.png
  project/app/src/main/res/mipmap-xhdpi/check_comments.png
  project/app/src/main/res/mipmap-xhdpi/check_comments_foreground.png
  project/app/src/main/res/mipmap-xhdpi/check_comments_round.png
  project/app/src/main/res/mipmap-xhdpi/checkx.png
  project/app/src/main/res/mipmap-xhdpi/directx.png
  project/app/src/main/res/mipmap-xxhdpi/check_comments.png
  project/app/src/main/res/mipmap-xxhdpi/check_comments_foreground.png
  project/app/src/main/res/mipmap-xxhdpi/check_comments_round.png
  project/app/src/main/res/mipmap-xxhdpi/check_commentxx.png
  project/app/src/main/res/mipmap-xxhdpi/directxx.png
  project/app/src/main/res/mipmap-xxxhdpi/check_comments.png
  project/app/src/main/res/mipmap-xxxhdpi/check_comments_foreground.png
  project/app/src/main/res/mipmap-xxxhdpi/check_comments_round.png
  project/app/src/main/res/mipmap-xxxhdpi/check_commenxxx.png
  project/app/src/main/res/mipmap-xxxhdpi/directxxx.png
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsFragmentTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Comment/CommentAdapterSpy.kt
Labels: code, design, development team, medium

#333 Feature/313
  project/app/build.gradle
Labels: easy, infrastructure, refactoring, urgent

#328 Feature/121 2
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/Entities/User/UserMocker.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginModel.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginView.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingModel.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingPresenter.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileView.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
  project/app/src/main/java/com/nexte/nexte/UserSingleton.kt
  project/app/src/main/res/layout/activity_main.xml
  project/app/src/main/res/layout/activity_ranking.xml
  project/app/src/main/res/layout/activity_show_profile.xml
  project/app/src/main/res/layout/ranking_fragment.xml
  project/app/src/main/res/layout/row_ranking.xml
  project/app/src/main/res/menu/bottom_navigation.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginModelTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingFragmentTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingModelTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingViewTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileViewTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorkerTest.kt
Labels: development team, easy, mds, refactoring

#342 Feature/138
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragmentTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorkerTest.kt
Labels: code, development team, eps, medium
