Repository fga-gpp-mds/2018.1_Nexte, pull requests merged in 2018-06, with the labels that each got.

#346 Feature/130
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchFragment.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchInteractor.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchModel.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchPresenter.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchWorker.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchFragmentTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchModelTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchWorkerTest.kt
Labels: code, development team, eps, medium

#347 Feature/326
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsFragment.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileInteractor.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedFragment.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedModel.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedPresenter.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListFragment.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListModel.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginPresenter.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchFragment.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchModel.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
  project/app/src/main/res/drawable/edge_photo.xml
  project/app/src/main/res/drawable/edge_text_edit_profile.xml
  project/app/src/main/res/layout/activity_edit_profile.xml
  project/app/src/main/res/layout/row_ranking.xml
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileFragmentTest.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfilePresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileWorkerTest.kt
Labels: design, development team, eps, mds, refactoring

#367 Feature/129
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/Entities/Story/Story.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedFragment.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedInteractor.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedModel.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedPresenter.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedWorker.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedModelTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedViewTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedWorkerTest.kt
Labels: code, development team, eps, medium

#369 Feature/141
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsFragment.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/Comment.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapter.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentManager.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Like/LikeAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryAdapterRealm.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Comment/CommentAdapterSpy.kt
Labels: code, development team, eps, medium

#395 Feature/339
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedFragment.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/res/drawable-hdpi/ic_challenge.png
  project/app/src/main/res/drawable-hdpi/ic_feed.png
  project/app/src/main/res/drawable-hdpi/ic_ranking.png
  project/app/src/main/res/drawable-hdpi/icon_challenge.png
  project/app/src/main/res/drawable-hdpi/icon_feed.png
  project/app/src/main/res/drawable-hdpi/icon_profile.png
  project/app/src/main/res/drawable-hdpi/icon_ranking.png
  project/app/src/main/res/drawable-mdpi/ic_challenge.png
  project/app/src/main/res/drawable-mdpi/ic_feed.png
  project/app/src/main/res/drawable-mdpi/ic_ranking.png
  project/app/src/main/res/drawable-mdpi/icon_challenge.png
  project/app/src/main/res/drawable-mdpi/icon_feed.png
  project/app/src/main/res/drawable-mdpi/icon_profile.png
  project/app/src/main/res/drawable-mdpi/icon_ranking.png
  project/app/src/main/res/drawable-xhdpi/ic_challenge.png
  project/app/src/main/res/drawable-xhdpi/ic_feed.png
  project/app/src/main/res/drawable-xhdpi/ic_ranking.png
  project/app/src/main/res/drawable-xhdpi/icon_challenge.png
  project/app/src/main/res/drawable-xhdpi/icon_feed.png
  project/app/src/main/res/drawable-xhdpi/icon_profile.png
  project/app/src/main/res/drawable-xhdpi/icon_ranking.png
  project/app/src/main/res/drawable-xxhdpi/ic_challenge.png
  project/app/src/main/res/drawable-xxhdpi/ic_feed.png
  project/app/src/main/res/drawable-xxhdpi/ic_ranking.png
  project/app/src/main/res/drawable-xxhdpi/icon_challenge.png
  project/app/src/main/res/drawable-xxhdpi/icon_feed.png
  project/app/src/main/res/drawable-xxhdpi/icon_profile.png
  project/app/src/main/res/drawable-xxhdpi/icon_ranking.png
  project/app/src/main/res/drawable/bottom_navigation_colors.xml
  project/app/src/main/res/layout/activity_main.xml
  project/app/src/main/res/menu/bottom_navigation.xml
  project/app/src/main/res/values/colors.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/main/res/values/styles.xml
Labels: code, design, development team

#398 Hotfix/1.2 - Testes com JSON =)
  project/app/build.gradle
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListWorkerTest.kt
Labels: bug, code, enhancement, test

#399 Feature/135
  project/app/build.gradle
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchFragment.kt
  project/app/src/main/res/drawable-hdpi/icon_date.png
  project/app/src/main/res/drawable-hdpi/icon_time.png
  project/app/src/main/res/drawable-mdpi/icon_date.png
  project/app/src/main/res/drawable-mdpi/icon_time.png
  project/app/src/main/res/drawable-xhdpi/icon_date.png
  project/app/src/main/res/drawable-xhdpi/icon_time.png
  project/app/src/main/res/drawable-xxhdpi/icon_date.png
  project/app/src/main/res/drawable-xxhdpi/icon_time.png
  project/app/src/main/res/font/roboto_black.ttf
  project/app/src/main/res/font/roboto_black_italic.ttf
  project/app/src/main/res/font/roboto_bold.ttf
  project/app/src/main/res/font/roboto_bold_condensed.ttf
  project/app/src/main/res/font/roboto_bold_condensed_italic.ttf
  project/app/src/main/res/font/roboto_bold_italic.ttf
  project/app/src/main/res/font/roboto_condensed.ttf
  project/app/src/main/res/font/roboto_condensed_italic.ttf
  project/app/src/main/res/font/roboto_italic.ttf
  project/app/src/main/res/font/roboto_light.ttf
  project/app/src/main/res/font/roboto_light_italic.ttf
  project/app/src/main/res/font/roboto_medium.ttf
  project/app/src/main/res/font/roboto_medium.xml
  project/app/src/main/res/font/roboto_medium_italic.ttf
  project/app/src/main/res/font/roboto_regular.ttf
  project/app/src/main/res/font/roboto_thin_italic.ttf
  project/app/src/main/res/font/roboto_thin_italic.xml
  project/app/src/main/res/layout/activity_challenger.xml
  project/app/src/main/res/layout/activity_challenger_received.xml
  project/app/src/main/res/layout/activity_match.xml
  project/app/src/main/res/layout/fragment_nochallenge.xml
  project/app/src/main/res/layout/row_match_info.xml
  project/app/src/main/res/layout/row_match_sets.xml
  project/app/src/main/res/layout/row_match_time.xml
  project/app/src/main/res/layout/row_match_wo.xml
  project/app/src/main/res/values/colors.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/UserSingletonTest.kt
Labels: design, easy, refactoring

#401 Added UserCategory in HelpForRealm for tests with this
  project/app/src/test/java/com/nexte/nexte/HelpForRealm.kt
Labels: bug, test

#405 Feature/384
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
Labels: code, design, easy

#415 Feature/356
  project/app/build.gradle
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/MatchModelTestTest.kt
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/TestActivityMatch.java
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/TestFiveSetsSendSuccess.java
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/TestOneSetSendSuccess.java
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/TestSendChallenge.java
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/TestThreeSetsSendSuccess.java
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/TestWOChallengerSuccess.java
  project/app/src/main/res/layout/row_match_info.xml
  project/app/src/main/res/layout/row_match_sets.xml
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchModelTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchWorkerTest.kt
Labels: hard, mds, test

#418 Feature/351
  project/app/src/androidTest/java/com/nexte/nexte/CommentsTest.java
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/MatchModelTestTest.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Story/StoryAdapterSpy.kt
Labels: code, test

#416 Feature/354
  project/app/build.gradle
  project/app/src/androidTest/java/com/nexte/nexte/LikeListTest/LikeListInstrumentationTest.java
  project/app/src/androidTest/java/com/nexte/nexte/MatchScene/MatchModelTestTest.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListPresenter.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListWorker.kt
  project/app/src/main/res/drawable/ic_launcher_loginbackground.xml
  project/app/src/main/res/mipmap-anydpi-v26/calendar_logo.xml
  project/app/src/main/res/mipmap-anydpi-v26/calendar_logo_round.xml
  project/app/src/main/res/mipmap-anydpi-v26/clock_logo.xml
  project/app/src/main/res/mipmap-anydpi-v26/clock_logo_round.xml
  project/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  project/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  project/app/src/main/res/mipmap-anydpi-v26/nexte_logo.xml
  project/app/src/main/res/mipmap-anydpi-v26/nexte_logo_round.xml
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListWorkerTest.kt
Labels: code, test

#414 Feature/402
  docs/Sprints/Sprint14/Sprint14-Planejamento.md
  mkdocs.yml
  project/app/build.gradle
Labels: documentation, easy, scrum master

#412 Feature/383
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/res/layout/activity_show_profile.xml
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragmentTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenterTest.kt
Labels: code, design, development team

#417 Feature/353
  project/app/build.gradle
  project/app/src/androidTest/java/com/nexte/nexte/FeedInstrumentalTest/ActivityTest.java
  project/app/src/androidTest/java/com/nexte/nexte/FeedInstrumentalTest/CommentsFeedTest.java
  project/app/src/androidTest/java/com/nexte/nexte/FeedInstrumentalTest/LikeFeedTest.java
  project/app/src/main/java/com/nexte/nexte/Entities/Story/Story.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedManager.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedPresenter.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedWorker.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedModelTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListInteractorTest.kt
Labels: mds, test

#409 Feature/391
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingModel.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingPresenter.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/LikeListScene/LikeListInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingModelTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingPresenterTest.kt
Labels: code, design, medium

#419 Feature/394
  docs/CentralizacaoInformacoes.md
  project/app/src/androidTest/java/com/nexte/nexte/FixedRankingTest.java
  project/app/src/androidTest/java/com/nexte/nexte/MainActivityTest2.java
  project/app/src/androidTest/java/com/nexte/nexte/MainActivityTest3.java
  project/app/src/androidTest/java/com/nexte/nexte/MainActivityTest4.java
Labels: devops, easy, infrastructure

#420 Feature/379
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/icon_app-web.png
  project/app/src/main/icon_app_dark-web.png
  project/app/src/main/icon_app_transparent-web.png
  project/app/src/main/icon_app_white-web.png
  project/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-hdpi/icon_app_dark.png
  project/app/src/main/res/mipmap-hdpi/icon_app_transparent.png
  project/app/src/main/res/mipmap-hdpi/icon_app_white.png
  project/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-mdpi/icon_app_dark.png
  project/app/src/main/res/mipmap-mdpi/icon_app_transparent.png
  project/app/src/main/res/mipmap-mdpi/icon_app_white.png
  project/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-xhdpi/icon_app_dark.png
  project/app/src/main/res/mipmap-xhdpi/icon_app_transparent.png
  project/app/src/main/res/mipmap-xhdpi/icon_app_white.png
  project/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-xxhdpi/icon_app_dark.png
  project/app/src/main/res/mipmap-xxhdpi/icon_app_transparent.png
  project/app/src/main/res/mipmap-xxhdpi/icon_app_white.png
  project/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  project/app/src/main/res/mipmap-xxxhdpi/icon_app_dark.png
  project/app/src/main/res/mipmap-xxxhdpi/icon_app_transparent.png
  project/app/src/main/res/mipmap-xxxhdpi/icon_app_white.png
  project/app/src/main/res/values/ic_launcher_background.xml
  project/app/src/main/res/values/icon_app_dark_background.xml
Labels: design, easy

#422 feature/376
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
  project/app/src/main/res/drawable/edge_text_profile_gray.xml
  project/app/src/main/res/drawable/edge_text_profile_green.xml
  project/app/src/main/res/drawable/edge_text_profile_red.xml
  project/app/src/main/res/layout/activity_edit_profile.xml
  project/app/src/main/res/layout/activity_show_profile.xml
  project/app/src/main/res/values/colors.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragmentTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenterTest.kt
Labels: code, design, development team, easy, refactoring

#421 Feature/403
  docs/Sprints/Sprint13/Sprint13-Resultados.md
  mkdocs.yml
  project/projectFilesBackup1/.idea/workspace.xml
  project/projectFilesBackup2/.idea/workspace.xml
Labels: documentation, easy, scrum master

#423 Feature/372
  project/app/build.gradle
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/build.gradle
Labels: devops, easy, enhancement, infrastructure

#430 Feature/378
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/res/layout/activity_show_profile.xml
  project/app/src/main/res/values/array.xml
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenterTest.kt
Labels: code, development team

#431 Feature/380
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/FeedMocker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/User/User.kt
  project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListInteractor.kt
  project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListWorker.kt
  project/app/src/test/java/com/nexte/nexte/Entities/RealmTests.kt
  project/app/src/test/java/com/nexte/nexte/PlayerTest.kt
  project/app/src/test/java/com/nexte/nexte/PlayersListScene/PlayersListInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/PlayersListScene/PlayersListWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingWorkerTest.kt
Labels: code, development team, eps, medium

#428 Feature/390
  project/app/src/main/icon_triangle_lose-web.png
  project/app/src/main/icon_triangle_win-web.png
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapter.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeManager.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/res/layout/activity_show_profile.xml
  project/app/src/main/res/layout/columns_challenges_show.xml
  project/app/src/main/res/mipmap-hdpi/icon_triangle_lose.png
  project/app/src/main/res/mipmap-mdpi/icon_triangle_lose.png
  project/app/src/main/res/mipmap-xhdpi/icon_triangle_lose.png
  project/app/src/main/res/mipmap-xxhdpi/icon_triangle_lose.png
  project/app/src/main/res/mipmap-xxxhdpi/icon_triangle_lose.png
  project/app/src/main/res/mipmap-xxxhdpi/icon_triangle_win.png
  project/app/src/test/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapterSpy.kt
  project/app/src/test/java/com/nexte/nexte/Entities/User/UserAdapterSpy.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfileModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenterTest.kt
Labels: development team, enhancement, medium

#432 Hotfix/1.3 - Arrumado o pipeline da dev e aumento na cobertura de testes para 81%
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginWorker.kt
  project/app/src/test/java/com/nexte/nexte/Entities/User/UserAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/User/UserCategory/UserCategoryAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/HelpForRealm.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingPresenterTest.kt
Labels: architecture, bug, code, pipeline

#445 Feature/355 - 83% de cobertura de testes total e 91% na login scene
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginInteractor.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginWorker.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginModelTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginWorkerTest.kt
Labels: code, development team, enhancement, eps, mds, test, testing

#448 hotfix/1.5
  project/gradle.properties
Labels: urgent

#450 Feature/449 - 88% de cobertura de testes
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Like/LikeAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryMocker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/User/UserCategory/UserCategoryAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginView.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Challenge/ChallengeManagerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Challenge/ChallengeRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Comment/CommentMockerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Comment/CommentRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Like/LikeAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Like/LikeManagerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Like/LikeRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Story/StoryAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Story/StoryMockerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/User/UserAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/User/UserCategory/UserCategoryAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/HelpForRealm.kt
Labels: code, eps, medium, test

#452 Feature/444
  docs/Sprints/Sprint15/Sprint15-Planejamento.md
  mkdocs.yml
Labels: documentation, easy, scrum master

#454 Feature/453
  project/app/src/main/AndroidManifest.xml
Labels: bug, mds

#463 Hotfix/1.6 - Corrigido testes que estava falhando
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingPresenter.kt
  project/app/src/test/java/com/nexte/nexte/RankingScene/RankingPresenterTest.kt
Labels: code, test

#447 Feature/375
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchPresenter.kt
  project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListFragment.kt
  project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListModel.kt
  project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListPresenter.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
  project/app/src/main/res/drawable/button_bg_stroke.xml
  project/app/src/main/res/layout/activity_challenger_sent.xml
  project/app/src/main/res/layout/columns_challenged.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/PlayersListScene/PlayersListModelTest.kt
  project/app/src/test/java/com/nexte/nexte/PlayersListScene/PlayersListPresenterTest.kt
  project/default-detekt-config.yml
Labels: code, development team, eps, medium

#465 Feature/436
  docs/EPS/EVM_vs_Burndown.md
Labels: communication, documentation, easy, eps, scrum master

#468 Feature/443
  docs/Sprints/Sprint13/Sprint13-Resultados.md
  docs/Sprints/Sprint14/Sprint14-Resultados.md
  mkdocs.yml
Labels: documentation, easy, eps, scrum master

#471 Feature/407
  docs/README.md
  docs/index.md
  mkdocs.yml
Labels: communication, design, documentation, eps, medium

#473 Feature/461
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingFragment.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileFragment.kt
  project/app/src/main/res/values/strings.xml
Labels: architecture, bug, design, development team

#474 Feature/439
  docs/Testes/TestesUsabilidade.md
  mkdocs.yml
Labels: documentation, easy, eps

#475 Feature/467
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeMocker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/User/User.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchFragment.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/EditProfileScene/EditProfileWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenterTest.kt
Labels: code, development team, refactoring

#483 Feature/438 - Pequenos ajustes nas documentações de EPS
  docs/EPS/MetodologiaDoProjeto.md
  docs/EPS/PlanoDeQualidade/Metricas.md
  docs/EPS/TAP.md
Labels: documentation, easy, eps

#478 Feature/434
  docs/EPS/Pipeline.md
  mkdocs.yml
Labels: devops, documentation, easy, eps, pipeline

#481 Feature/456
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsFragment.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentMocker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/FeedMocker.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryAdapter.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryManager.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedFragment.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedInteractor.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedManager.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedModel.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedPresenter.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedWorker.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListFragment.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListModel.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Comment/CommentAdapterSpy.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Story/StoryAdapterSpy.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Story/StoryManagerTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedModelTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedViewTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedWorkerTest.kt
Labels: bug, hard, refactoring

#488 Feature/464 - Post Mortem 2 e Fechamento do Projeto
  docs/PostMortem/PostMortemRelease2-FechamentoDoProjeto.md
  docs/Sprints/Sprint15/Sprint15-Resultados.md
  mkdocs.yml
Labels: documentation, eps, medium, scrum master

#492 Feature/472
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/res/layout/activity_comments.xml
Labels: bug, code

#491 Feature/470
  project/app/src/main/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Like/LikeAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Story/StoryAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/Entities/User/UserCategory/UserCategoryAdapterRealm.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Comment/CommentAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Like/LikeAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/Story/StoryAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/User/UserAdapterRealmTest.kt
  project/app/src/test/java/com/nexte/nexte/Entities/User/UserCategory/UserCategoryAdapterRealmTest.kt
Labels: code, development team, test

#495 Feature/494
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsFragment.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListFragment.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListPresenter.kt
  project/app/src/main/res/layout/row_comments.xml
  project/app/src/main/res/layout/row_likes.xml
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
Labels: bug, code

#489 Feature/487 - Integração da match com servidor
  mkdocs.yml
  project/app/src/main/java/com/nexte/nexte/ChallengeTabsFragment.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/Challenge.kt
  project/app/src/main/java/com/nexte/nexte/Entities/Challenge/ChallengeAdapterRealm.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchFragment.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchModel.kt
  project/app/src/main/java/com/nexte/nexte/MatchScene/MatchWorker.kt
  project/app/src/main/java/com/nexte/nexte/PlayersListScene/PlayersListWorker.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/res/layout/activity_match.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchModelTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/MatchScene/MatchWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/PlayersListScene/PlayersListModelTest.kt
  project/app/src/test/java/com/nexte/nexte/PlayersListScene/PlayersListPresenterTest.kt
Labels: code, eps, medium, server
