Repository fga-gpp-mds/2018.1_Nexte, pull requests merged in 2018-03, with the labels that each got.

#31 Adição do documento de visão
  .github/issue_template.md
  .gitignore
  Docs/DocVisao.md
  Docs/EPS/TAP.md
Labels: MDS, documentation

#50 Feature/4
  Docs/EPS/EAP.md
Labels: EP, documentation

#52 Feature/08
  Docs/MDS/DocEspecificacaoSuplementar.md
Labels: MDS, documentation

#81 Feature/62
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginPresenter.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginWorker.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfile/ShowProfileInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfile/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfile/ShowProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfile/ShowProfileView.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfile/ShowProfileWorker.kt
  project/app/src/main/res/layout/activity_main.xml
Labels: MDS

#86 Feature/71
  Docs/EPS/GestaoDeRisco.md
Labels: EP, documentation

#85 Feature/63
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedInteractor.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedModel.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedPresenter.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedView.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedWorker.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
Labels: MDS, code, medium

#89 Feature/09
  Docs/MDS/DocPrototipodeBaixaFidelidade.md
Labels: easy

#84 Feature/61
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileInteractor.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileView.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileWorker.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginIteractor.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileView.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
Labels: MDS, code, medium

#83 Feature/29
  Docs/MDS/DocFolhaEstilo.md
Labels: MDS, documentation, medium

#88 Feature/66
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeModel.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeView.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeWorker.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
Labels: MDS, medium

#87 Feature/65
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsInteractor.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsView.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
Labels: MDS, code, medium
