Repository fga-gpp-mds/2018.1_Nexte, pull requests merged in 2018-04, with the labels that each got.

#150 Feature/64
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/RankScene/RankInteractor.kt
  project/app/src/main/java/com/nexte/nexte/RankScene/RankModel.kt
  project/app/src/main/java/com/nexte/nexte/RankScene/RankPresenter.kt
  project/app/src/main/java/com/nexte/nexte/RankScene/RankView.kt
  project/app/src/main/java/com/nexte/nexte/RankScene/RankWorker.kt
Labels: MDS, code

#164 Feature/92
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileActivity.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileModel.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfilePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileView.kt
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileWorker.kt
  project/app/src/main/res/layout/activity_main.xml
  project/app/src/main/res/layout/activity_show_profile.xml
  project/app/src/main/res/values/dimens.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/main/res/values/styles.xml
Labels: MDS, code

#180 feature/179
  docs/Sprints/Sprint5/Sprint5-Planejamento.md
Labels: documentation, easy, eps

#183 Feature/98
  docs/EPS/DefinicaoDeProdutividade.md
  docs/EPS/GestaoDeRisco.md
  docs/Sprints/Sprint4/Sprint4-Planejamento.md
  docs/Sprints/Sprint4/Sprint4-Resultados.md
  mkdocs.yml
Labels: documentation, eps, medium, scrum master

#175 feature/174
  docs/MDS/DocFolhaEstilo.md
Labels: development team, documentation, easy, refactoring

#185 Feature/169
  docs/MDS/DocPrototipodeAltaFidelidade.MD
Labels: documentation, easy, enhancement, mds

#189 Feature/104
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedView.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListInteractor.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListModel.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListPresenter.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListView.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListWorker.kt
  project/app/src/main/res/layout/activity_list_like.xml
  project/app/src/main/res/layout/row_feed.xml
  project/app/src/main/res/layout/row_likes.xml
Labels: code, mds, medium

#196 Feature/105
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingInteractor.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingModel.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingPresenter.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingView.kt
  project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt
  project/app/src/main/res/layout/activity_ranking.xml
  project/app/src/main/res/layout/row_ranking.xml
Labels: code, development team, medium, refactoring

#187 Feature/103
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedInteractor.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedManager.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedMocker.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedModel.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedPresenter.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedView.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedWorker.kt
  project/app/src/main/res/layout/activity_feed_view.xml
  project/app/src/main/res/layout/row_feed.xml
  project/app/src/main/res/values/colors.xml
  project/build.gradle
Labels: code, development team, mds

#209 Hotfix/0.4
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedModelTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedWorkerTest.kt
Labels: bug, code, eps, infrastructure, urgent

#210 Feature/200
  docs/CentralizacaoInformacoes.md
  mkdocs.yml
Labels: documentation, easy, eps, studies

#216 Feature/215
  .github/CONTRIBUTING.md
  docs/index.md
Labels: documentation, easy, eps, po

#220 Feature/195
  docs/PostMortem/PostMortemRelease1.md
  mkdocs.yml
Labels: communication, documentation, eps, mds

#198 Feature/108
  .github/CONTRIBUTING.md
  .gitignore
  .gitlab-ci.yml
  README.md
  docker-compose.yml
  docker/Dockerfile
  docker/build.sh
  docker/static_analysis.sh
  docker/test.sh
  project/Gemfile
  project/app/build.gradle
  project/app/src/main/AndroidManifest.xml
  project/fastlane/Appfile
  project/fastlane/Fastfile
  project/fastlane/Pluginfile
  project/fastlane/README.md
  project/fastlane/metadata/android/pt-BR/full_description.txt
  project/fastlane/metadata/android/pt-BR/images/icon.png
  project/fastlane/metadata/android/pt-BR/short_description.txt
  project/fastlane/metadata/android/pt-BR/title.txt
  project/fastlane/metadata/android/pt-BR/video.txt
  project/fastlane/report.xml
Labels: devops, eps, infrastructure

#221 Feature/179
  docs/Sprints/Sprint5/Sprint5-Resultados.md
  mkdocs.yml
Labels: documentation, eps, medium, scrum master

#236 Feature/207
  docs/EPS/TAP.md
  docs/Sprints/Sprint6/Sprint6-Resultados.md
  mkdocs.yml
Labels: documentation, eps, medium, scrum master

#238 Feature/230
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedView.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/build.gradle
Labels: code, development team, enhancement, eps, infrastructure

#240 Feature/112
  docs/MDS/DocArquitetura.md
  docs/MDS/DocDiagram/CommentsDiagram.asta
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsInteractor.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsModel.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsPresenter.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsView.kt
  project/app/src/main/java/com/nexte/nexte/CommentsScene/CommentsWorker.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedView.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListModel.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListPresenter.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListView.kt
  project/app/src/main/java/com/nexte/nexte/LikeListScene/LikeListWorker.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/res/layout/activity_comments.xml
  project/app/src/main/res/layout/row_comments.xml
  project/app/src/main/res/layout/row_feed.xml
  project/app/src/main/res/layout/row_likes.xml
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsModelTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/CommentsScene/CommentsWorkerTest.kt
Labels: code, development team, medium

#242 Feature/113
  docs/MDS/DocArquitetura.md
  docs/MDS/DocDiagram/UpdatedChallengeDiagram.asta
  project/app/build.gradle
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeInteractor.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeMocker.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeModel.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengePresenter.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeView.kt
  project/app/src/main/java/com/nexte/nexte/ChallengeScene/ChallengeWorker.kt
  project/app/src/main/java/com/nexte/nexte/EditProfileScene/EditProfileWorker.kt
  project/app/src/main/java/com/nexte/nexte/FeedScene/FeedManager.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/java/com/nexte/nexte/UserSingleton.kt
  project/app/src/main/res/layout/activity_challenger.xml
  project/app/src/main/res/layout/activity_main.xml
  project/app/src/main/res/layout/columns_challenged.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeMockerTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeModelTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengePresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeViewTest.kt
  project/app/src/test/java/com/nexte/nexte/ChallengeScene/ChallengeWorkerTest.kt
Labels: code, development team, enhancement

#241 Feature/111
  project/app/build.gradle
  project/app/src/main/java/com/nexte/nexte/ShowProfileScene/ShowProfileView.kt
  project/app/src/main/res/layout/activity_show_profile.xml
  project/build.gradle
  project/gradle.properties
Labels: code, development team, medium

#208 Feature/170
  project/app/build.gradle
  project/app/src/androidTest/java/com/nexte/nexte/MainActivityUITest.kt
  project/app/src/main/AndroidManifest.xml
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginInteractor.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginModel.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginPresenter.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginView.kt
  project/app/src/main/java/com/nexte/nexte/LoginScene/LoginWorker.kt
  project/app/src/main/java/com/nexte/nexte/MainActivity.kt
  project/app/src/main/res/layout/activity_login_view.xml
  project/app/src/main/res/layout/activity_main.xml
  project/app/src/main/res/network_security_config.xml
  project/app/src/main/res/values/strings.xml
  project/app/src/main/res/values/styles.xml
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedModelTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/FeedScene/FeedWorkerTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginInteractorTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginModelTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginPresenterTest.kt
  project/app/src/test/java/com/nexte/nexte/LoginScene/LoginWorkerTest.kt
  project/default-detekt-config.yml
Labels: architecture, eps, infrastructure
